import sys
from datetime import date
from itertools import repeat, chain
from urllib.request import urlopen

from simulator import Team
from teams import get_teams_file

gender = "m"
if "-w" in sys.argv:
    gender = "w"
elif "-m" in sys.argv:
    gender = "m"

TEAMS_FILENAME = f"data/teams_{date.today().year}{gender}.json"


def randomnumbers(num: int):
    for x in urlopen(
            f"https://www.random.org/integers/?num={num}&min=0&max=999&col=1&base=10&format=plain&rnd=new"
    ):
        yield int(x)


if "--test" in sys.argv:
    random_generator = repeat(0)
elif "--partial" in sys.argv:
    with open(sys.argv[sys.argv.index("--partial") + 1]) as f:
        random_generator = [int(x) for x in f]
    random_generator = chain(
        random_generator, randomnumbers(63 - len(random_generator))
    )
else:
    print(
        "Using numbers generated by random.org. Do not use faster than you could manually refresh a webpage, there is a quota per IP address per day, and you are otherwise subject to their guidelines at random.org/clients"
    )
    random_generator = randomnumbers(63)


divisions = get_teams_file(TEAMS_FILENAME)
division_matchups = [
    (divisions[0].name, divisions[1].name),
    (divisions[2].name, divisions[3].name),
]
for i in range(4):
    for division in divisions:
        division.play_round(random_generator)
final_four = {division.name: division.winner() for division in divisions}
championship = [
    Team.play_game(final_four[div_a], final_four[div_b], next(random_generator))
    for div_a, div_b in division_matchups
]
champion = Team.play_game(*championship, next(random_generator))

print("\n\nFinalFour\n" + championship[0].name + ", " + championship[1].name)
print("\nChamp: " + champion.name)
